name: Custom-Message-Menager
version: '1.0-Release'
main: pl.CustomMessageMenager.customMessageMenagerCMM.CustomMessageMenagerCMM
api-version: '1.21'
author: Xraysigma
commands:
  cmm:
    description: Custom Message Manager
    usage: /cmm reload
    permission: cmm.reload

permissions:
  cmm.reload:
    default: op

